### ISSUE TITLE
branch help protocol is confusing with/without xet

### ISSUE THREAD

**Issue by xdssio** [xetdata/pyxet#104]
When using pyxet CLI to create a branch, the example is to use `xet://`, but in the annotation it is without (`<user>/<project>` )
```
xet branch make --help
Usage: xet branch make [OPTIONS] REPO SRC_BRANCH DEST_BRANCH

  make a new branch copying another branch. Branch names with "/" in them are
  not supported.

  Example: Create a new branch from the main branch

      xet branch make xet://user/repo main new_branch ##### ← with xet

Arguments:
  REPO         a repository name <user>/<project>  [required] ##### ← without xet
  SRC_BRANCH   src branch to copy  [required]
  DEST_BRANCH  new branch name  [required]
```

Currently it only works with `xet://`
```
 File "/opt/homebrew/lib/python3.11/site-packages/pyxet/cli.py", line 526, in make
    assert(fs.protocol == 'xet')
           ^^^^^^^^^^^^^^^^^^^^

AssertionError
```

## Expected
Best it should work either way.
If one way, I would prefer no `xet://` as it's an fsspec detail and not a CLI one and less to write.

We can use full URL later of we're thinking of integrating with other Git platforms...

**Comment by seanses** [comment]
This was actually fixed. Try the latest pyxet release?
