### ISSUE TITLE
Feature request: `xet sync` command

### ISSUE THREAD

**Issue by znation** [xetdata/pyxet#16]
Similar to the `aws s3 sync` command, I'd like to be able to sync local or remote paths/URLs into a xet repo. Specifically, it would be nice to be able to have:

```
xet sync <from> <to>
```

Where either `<to>` or `<from>` can be either of:
* A local filesystem file or folder path (if folder, assumed to be recursive sync)
* A URL (including a `xet://` URL, or anything else that supports fsspec)

**Comment by erinys** [comment]
Tracked internally with https://github.com/xetdata/xethub/issues/3484.
