### ISSUE TITLE
[pyxet] Transaction size too big leading to 504

### ISSUE THREAD

**Issue by seanses** [xetdata/pyxet#17]
Getting `HTTP status server error (504 Gateway Timeout) for url (https://xethub.com/api/xet/repos/XetHub/The-Real-Laion400M/commits)`.

**Comment by ylow** [comment]
Workaround:
```
import pyxet.commit_transaction
pyxet.commit_transaction.TRANSACTION_LIMIT=1024
```

**Comment by ylow** [comment]
Large transactions may take a while to upload... While we optimize the backend.... the simplest workaround for now is to reduce the transaction size.

**Comment by hoytak** [comment]
Reduced the maximum, closing issue.
