### ISSUE TITLE
Add mode 'a' and 'ab' for appending.

### ISSUE THREAD

**Issue by xdssio** [xetdata/pyxet#30]
Currently, we can only open files as 'r' or 'w'. 
To append to a big CSV, to a text file or stream arrow, we must create apend to local file and use `xet cp`.
It also means we can't do it from python. (we can append, but not write).

An alternative: `fs.open(path, mode='ab')`

Example
```
import pyxet
import pandas as pd

df = pd.DataFrame([{'id': '123', 
				'gender': 'male','age':15, 
			        'topic': 'Student', 
			        'sign': 'Leo',
			        'date': '14,May,2004',
			        'text': "loved that review"}])

# Add The data straight to the cloud
fs = pyxet.XetFS()
target = f"xet://xdssio/blog_corpus/add-a-review/data/data.csv"
with fs.transaction:
	df.to_csv(fs.open(target, 'a'), mode='a', index=False, header=False) 
```

**Comment by ylow** [comment]
This is actually very difficult for big files. The easy way is to download the file, then append. Technically the MerkleTree structure can enable this efficiently, but it will plumb very deep.
