### ISSUE TITLE
Lazy and materialize

### ISSUE THREAD

**Issue by xdssio** [xetdata/pyxet#32]
> [Private discussion](https://www.notion.so/xethub/The-Case-for-lazy-d7b1ce10d6af43f2812b8ccdb63ca365) 
## Lazy and materialize
First suggestion on the table:  **XET_LAZY** should probably replace the **NO_SMUDGE**.
It's nicer messaging. 

Currently, to "materialize" a file, we use `git xet checkout <path> -- `, a more coherent option for pyxet could be 
`xet materialize <path>`.

Here are a few ideas to turn a file or folder recursively to a pointers:
* `xet dematerialize -r <path>`
* `xet melt ...`
* `xet fade ...`
* `xet point ...` 
* `xet pointer ...`

For **clone**, adding a parameter `--lazy`, `--materialize` is a nice.

## Local files
Another aspect is opening a local file. 
Not always can we keep a tab if a file has melted away at some point and we get code errors.

Using our file system, we can check if a file is a pointer, and either read it from the cloud or materialize it if needed.

```
import pyxet

fs = pyxet.XetFS()
fs.open('file.txt') # Should always work
```

**Comment by ylow** [comment]
Via xet cli there is no real way to get a pointer file so I think it should be unnecessary to expose users to the concept. The only path is `xet clone --no_smudge` which plumbs to `git xet clone --no_smudge`.

**Comment by allisonwhilden** [comment]
Quick note: we should remember to add lazy and materialize to our documentation for git xet. We don't currently have `xet clone` in the documentation, so we don't have to worry about removing it.

**Comment by seanses** [comment]
The related git-xet --lazy issue: https://github.com/xetdata/xethub/issues/4143

**Comment by ylow** [comment]
Implemented in git-xet as `git-xet materialize` and `git-xet dematerialize`
