### ISSUE TITLE
Do URLs need to start with xet://, https://, or nothing?

### ISSUE THREAD

**Issue by znation** [xetdata/pyxet#4]
There are mismatched protocols for URLs throughout the docs -- is this library-dependent for the integrations and intended to be different? Would it be possible to keep them aligned?

Examples include:

* both no protocol, and https:// on https://pyxet.readthedocs.io/en/latest/markdowns/filesystem.html
* both no protocol, and xet:// on https://pyxet.readthedocs.io/en/latest/markdowns/integrations.html

**Comment by rajatarya** [comment]
Addressed by #5.

**Comment by rajatarya** [comment]
Fixed in pyxet 0.0.3
