### ISSUE TITLE
xet rm doesn't work?

### ISSUE THREAD

**Issue by erinys** [xetdata/pyxet#44]
Not sure what caused this.

![Image](https://github.com/xetdata/pyxet/assets/1296134/31051e22-7c21-495b-995f-78606f47e9cc)

**Comment by ylow** [comment]
hmmm... just wondering. Can you try `xet rm xet://XetHub/FIFA23_dataset/main/archive`

**Comment by erinys** [comment]
ah, perhaps the trailing slash thing that #49 points to? I removed it already via some other means.

**Comment by ylow** [comment]
Trailing slash funniness. Though it should not return 500. I think there is another issue tracking error codes. Closing this one.
