### ISSUE TITLE
Slow initialization on large repo

### ISSUE THREAD

**Issue by znation** [xetdata/pyxet#53]
Tested by attempting to upload a new file to an existing large repo, but I assume this will probably repro with any usage (downloading too).

Repro:

```
(venv) ➜ xet cp arxiv.parquet xet://XetHub/RedPajama-Data-1T/parquet/arxiv.parquet
Copying /zdata/xets/RedPajama-Data-1T/arxiv.parquet to XetHub/RedPajama-Data-1T/parquet/arxiv.parquet...
Initializing repository on first access
Initialization complete
Synchronizing with remote
```

The command seems to hang at "Synchronizing with remote" for at least several minutes. It's been quite a while and the command still seems frozen there with no additional progress reported.

**Comment by ylow** [comment]
There is a large MDB synchronization happening at initialization of a repository. Many perf improvements need to be made there with the landing of MDBv2 and the shard hinting work.

**Comment by ylow** [comment]
This should be fixed by https://github.com/xetdata/xet-core/pull/91
