### ISSUE TITLE
xet cp needs a progress bar

### ISSUE THREAD

**Issue by znation** [xetdata/pyxet#54]
There is no progress indicated on `xet cp` commands. These can take quite a while so it appears to have hung. A progress bar would be great!

Related to #53 since the majority of the time spent there might be in the actual upload/download, but it's not clear when the synchronization is done and the upload/download has started.

**Comment by seanses** [comment]
Duplicate of https://github.com/xetdata/xethub/issues/3737

**Comment by znation** [comment]
@seanses Since this issue is public and that one is private, let's dupe that one against this one.

**Comment by Kelton8Z** [comment]
also the xet cp help text needs to indicate that cp only works for remote to remote

**Comment by seanses** [comment]
> also the xet cp help text needs to indicate that cp only works for remote to remote

That is not true. It works for (local | remote) <-> (local | remote)

**Comment by Kelton8Z** [comment]
> > also the xet cp help text needs to indicate that cp only works for remote to remote
> 
> 
> 
> That is not true. It works for (local | remote) <-> (local | remote)

You are right, could also be made clear in the help text. I only realized what "works everywhere" in Readme meant in hindsight 😅

**Comment by hoytak** [comment]
Progress bar in!
