### ISSUE TITLE
Feature request: pyxet git repo tooling

### ISSUE THREAD

**Issue by xdssio** [xetdata/pyxet#63]
Since we use git for many of our "state" information, the git params should be easily explored. 
This is mostly git wrappers which are ugly code using subprocess.
related: #62 
## Requirements:
```
# what branch are we on
$ pxyet.branch(local)

# return the commit hash and information 
$ pxyet.commit(local)

# which repo url - This can be more complicated if we use submodules, mounts, etc.
$ pyxet.get_url(local-dir)
```

**Comment by ylow** [comment]
`pyxet` does not actually maintain any active branch or commit information. The design is extremely stateless to allow you to read and write from any branch any location.

**Comment by erinys** [comment]
After discussion, we will not do this for now with the expectation that those who want to use Git will use Git Xet. Srini, Ann, Yonatan to continue considering PyXet/Git access patterns with use cases.
