### ISSUE TITLE
Not installable on arm64 Linux

### ISSUE THREAD

**Issue by znation** [xetdata/pyxet#7]
No valid packages for arm64 Linux appear to be published on PyPI.

Repro steps:

* Running on arm64 Ubuntu 22.04
* pip install pyxet

Expected: works
Actual:
```
ERROR: Could not find a version that satisfies the requirement pyxet (from versions: none)
ERROR: No matching distribution found for pyxet
```

Note: I'm using pip 22.0.2 and Python 3.10.6.

**Comment by ylow** [comment]
we have arm64 linux now!
